[WaveConfig]
  database = "./cldata/wave"
  listenIp = "127.0.0.1:7010"

  [WaveConfig.storage]
    # This is the default HTTPS server
    [WaveConfig.storage.default]
    provider = "http_v1"
    url = "https://standalone.storage.bwave.io/v1"
    version = "1"

[QueueConfig]
  queueDataStore = "./cldata/queue"
  # This is one day in seconds
  queueExpiry = 600
  # 1000 items
  subscriptionQueueMaxLength = 1000
  # 100MB
  subscriptionQueueMaxSize = 100
  # 10k items
  trunkingQueueMaxLength = 10000
  # 1GB
  trunkingQueueMaxSize = 1000
  # 30 seconds
  flushInterval = 1

[LocalConfig]
  listenAddr = "127.0.0.1:7012"

[PeerConfig]
  listenAddr = "127.0.0.1:7013"

[RoutingConfig]
PersistDataStore = "./cldata/persist"
RouterEntityFile = "./clrouter"
[[RoutingConfig.Router]]
  Namespace = "GyBfHOKpk7MJJZJDatu1EBQH5wbldv1zkWVBhgsGFEniSQ=="
  EntityHash = "GyBw0shMLZkvzS7b4lDIh8Rq7VwsQFIeyijLHAwIWyJB1w=="
  EntityLocation = "default"
  Address = "127.0.0.1:7003"
