[WaveConfig]
  database = "./drdata/wave"
  listenIp = "127.0.0.1:7002"
  defaultToUnrevoked = true
  
  [WaveConfig.storage]
    # This is the default HTTPS server
    [WaveConfig.storage.default]
    provider = "http_v1"
    url = "https://standalone.storage.bwave.io/v1"
    version = "1"

[QueueConfig]
  queueDataStore = "./drdata/queue"
  # This is one day in seconds
  queueExpiry = 600
  # 1000 items
  subscriptionQueueMaxLength = 1000
  # 100MB
  subscriptionQueueMaxSize = 100
  # 10k items
  trunkingQueueMaxLength = 10000
  # 1GB
  trunkingQueueMaxSize = 1000
  # 30 seconds
  flushInterval = 30

[LocalConfig]
  listenAddr = "127.0.0.1:7002"

[PeerConfig]
  listenAddr = "127.0.0.1:7003"

[RoutingConfig]
  PersistDataStore = "./drdata/persist"
  RouterEntityFile = "./router.ent"
  DesignatedNamespaceFiles = [
    "drproof.pem",
  ]
